#!/bin/zsh

#
# Function v executes a command on a remote Vagrant host.
# Thus invocation will only be successful if invoked in a
# vagrant enabled project.
#
# If inkoved with one arg will run the command on the remote host.
# In case of two or more args assumes the first arg to be
# a path to cd into, relative to the mounted shared folder,
# typically '/vagrant'. The remaining args form the command
# to be run on the guest.
#
# It assumes the vagrant host is up, i.e. 'vagrant up'
# has been called prior to calling the function.
# TODO: shall we automatically 'vagrant up' if the vm
# is not running?
#

local V='vagrant ssh -c'

case "$#" in
    0)
        print "Run a command in the context of a Vagrant Guest."
        print "The function expects at least 1 argument."
        ;;
    1)
        c="$V \"$1\""
        #echo $c
        eval ${c}
        ;;
    *)
        c="$V 'cd /vagrant/$1 && $@[2,$#]'"
        #echo $c
        eval ${c}
        ;;
esac
